name: CI + CD

on:
  push

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Compile
        run: echo Hellp, World
  
  
  DeployDev:
      name: Deploy to Dev
      if: github.event_name == 'pull_request'
      needs: [Build]
      runs-on: ubuntu-latest
      environment:
        name: Dev
        url: 'http://dev.myapp.com'
      steps:
        - name: Deploy
          run: echo I am deploying
        
  DeployStaging:
      name: Deploy to Staging
      if: github.event.name == 'refs/heads/main'
      needs: [Build]
      runs-on: ubuntu-latest
      environment:
        name: Staging
        url: 'http://test.myapp.com'
      steps:
        - name: Deploy
          run: echo I am deploying

  DeployProd:
      name: Deploy to Prod
      if: github.event_name == 'pull_request'
      needs: [DeployStaging]
      runs-on: ubuntu-latest
      environment:
        name: Prod
        url: 'http://www.myapp.com'
      steps:
        - name: Deploy
          run: echo I am deploying
